---
title: コールドスタンバイで「DataStoreException Record does not exist」エラーがスローされる
description: 説明
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM，コールドスタンバイ， DataStoreException, Adobe Experience Manager，レコードが存在しない，エラー，警告，警告
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 7f0f5035ea7cebd60f6ec7bda9de6225b6c602a4
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# コールドスタンバイで「DataStoreException Record does not exist」エラーがスローされる

## 説明


<b>環境</b>
Adobe Experience Manager

<b>問題</b>
専用ファイルデータストアを持つコールドスタンバイが、次のエラーと同様に、不明な blob id に対して警告をスローする。


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>原因</b>
これは単なる警告であり、エラーではありません。

これは、BLOB ID を読み込もうとする以外に、ファイルデータストアにバイナリがローカルに存在するかどうかを検証する手段がないことが原因です。
ID が読み込まれても、ログにはこの警告は表示されません。
ただし、見つからない場合は、スタンバイが同期する必要があることを認識するので、ログにこのような警告が表示されます。


## 解決策


<b>解決策</b>
これは設計どおりに動作し、ファイルデータストアに問題がないことは示しません。

BLOB ID が実際に見つからないことを確認するには、次の手順に従います。

1. 例えば、ログに見つからないと表示されているサンプル BLOB ID を使用します ( 例： `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`) をクリックします。
2. この例では、ファイルシステムのアドレスは次のようになります。 `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. スタンバイインスタンス上のファイルシステムを検索し、名前付きのファイルがファイルデータストアに存在するかどうかを確認します。
4. 内 `/repository/datastore`、 `list` ( 例： `ls -ald`) コマンド： `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. ファイルを表示し、BLOB ID が実際に見つからないことを確認できます。
